---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/amaur540/public_html/
    - /bin/cp -r dist/* $DEPLOYPATH
    - /bin/cp dist/.htaccess $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/wp-content/calendar-api
    - /bin/cp -r wp-content/calendar-api/* $DEPLOYPATH/wp-content/calendar-api/
    - /bin/mkdir -p $DEPLOYPATH/wp-content/instagram-api
    - /bin/cp -r wp-content/instagram-api/* $DEPLOYPATH/wp-content/instagram-api/
