

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <head>
        <title>Create React App</title>
        <meta name="description" content="Generated by create react app" />
      </head>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
